# Generated by Django 4.0.3 on 2022-03-18 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khatteeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middel_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Khottbah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('mosque', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('resources', models.TextField(max_length=2000)),
                ('language', models.CharField(blank=True, choices=[('ara', 'Arabic'), ('eng', 'English'), ('ord', 'Ordo')], default='ara', help_text='Kottbah Language', max_length=3)),
                ('Khatteeb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='khottab.khatteeb')),
            ],
        ),
    ]
