# Generated by Django 3.1.7 on 2022-03-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middel_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='Khatteeb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='khottab.imam'),
        ),
        migrations.DeleteModel(
            name='Khatteeb',
        ),
    ]
