# Generated by Django 3.1.7 on 2022-03-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0002_auto_20220329_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imam',
            old_name='Nationality',
            new_name='nationality',
        ),
    ]
