# Generated by Django 3.1.7 on 2022-03-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0003_auto_20220329_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khottbah',
            old_name='Khatteeb',
            new_name='imam',
        ),
    ]
