# Generated by Django 3.1.7 on 2022-03-30 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0004_auto_20220329_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khottbah',
            name='imam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='khottab.imam'),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='language',
            field=models.CharField(blank=True, choices=[('ara', 'Arabic'), ('eng', 'English'), ('ord', 'Ordo')], default='ara', help_text='The kottbah Language', max_length=3),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='resources',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
