# Generated by Django 3.1.7 on 2022-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0005_auto_20220330_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khottbah',
            name='resources',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
