# Generated by Django 3.1.7 on 2022-04-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0008_auto_20220409_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imam',
            options={'ordering': ['nationality'], 'permissions': (('can_view_imam', 'Can view imam'),)},
        ),
    ]
