# Generated by Django 3.1.7 on 2022-04-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0009_auto_20220411_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imam',
            options={'ordering': ['nationality'], 'permissions': (('can_view_imam', 'view'),)},
        ),
    ]
