# Generated by Django 3.1.7 on 2022-05-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0011_auto_20220411_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khottbah',
            options={'permissions': (('can_edite_khottbah', 'Can edite khottbah'),)},
        ),
    ]
