# Generated by Django 3.1.7 on 2022-05-11 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0012_auto_20220511_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular imam', primary_key=True, serialize=False),
        ),
    ]
