# Generated by Django 3.1.7 on 2022-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0015_auto_20220511_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
