# Generated by Django 3.1.7 on 2022-05-12 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0016_auto_20220511_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
