# Generated by Django 3.1.7 on 2022-05-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0022_auto_20220512_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khottbah',
            name='imam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imam', to='khottab.imam'),
        ),
    ]
