# Generated by Django 3.1.7 on 2022-05-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0023_auto_20220512_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khottbah',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='imam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khottab', to='khottab.imam'),
        ),
        migrations.AlterField(
            model_name='khottbah',
            name='resources',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
