# Generated by Django 3.1.7 on 2022-05-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0024_auto_20220525_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khottbah',
            name='language',
            field=models.CharField(blank=True, choices=[('arb', 'Arabic'), ('eng', 'English'), ('ord', 'Ordo')], default='ara', help_text='The kottbah Language', max_length=3),
        ),
    ]
