# Generated by Django 3.1.7 on 2022-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khottab', '0025_auto_20220525_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imam',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='imam',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='imam',
            name='middel_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='imam',
            name='nationality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
